import { randomBytes } from "node:crypto";

// 32 bytes = 256 bits of entropy, base64url so it drops straight into a URL
// with no escaping. The token *is* the credential for a share link, so it has
// to be long enough that guessing is hopeless — at this size it is.
const TOKEN_BYTES = 32;

export function generateShareToken() {
  return randomBytes(TOKEN_BYTES).toString("base64url");
}

// Tokens are always generated by us, so anything that isn't the right shape
// can be rejected before it ever reaches the database.
const TOKEN_PATTERN = /^[A-Za-z0-9_-]{43}$/;

export function isWellFormedToken(token: string) {
  return TOKEN_PATTERN.test(token);
}
