import { and, asc, desc, eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { type DocRole, documentMemberships, documents, users } from "@/db/schema";

// Every read goes through a membership join, so a user can only ever see
// documents they belong to — tenant isolation is enforced here, not in routes.

export const DOCS_PAGE_SIZE = 5;

// Paginated list. We fetch one extra row to know if there's a next page without
// a separate count query, then trim it off.
export async function listDocumentsForUser(
  userId: string,
  { limit = DOCS_PAGE_SIZE, offset = 0 }: { limit?: number; offset?: number } = {},
) {
  const rows = await db
    .select({
      id: documents.id,
      title: documents.title,
      role: documentMemberships.role,
      updatedAt: documents.updatedAt,
    })
    .from(documents)
    .innerJoin(documentMemberships, eq(documentMemberships.documentId, documents.id))
    .where(eq(documentMemberships.userId, userId))
    .orderBy(desc(documents.updatedAt))
    .limit(limit + 1)
    .offset(offset);

  const hasMore = rows.length > limit;
  return { docs: hasMore ? rows.slice(0, limit) : rows, hasMore };
}

// Lightweight role lookup for API authorization — just the caller's role, or null.
export async function getMembershipRole(documentId: string, userId: string) {
  const [row] = await db
    .select({ role: documentMemberships.role })
    .from(documentMemberships)
    .where(and(eq(documentMemberships.documentId, documentId), eq(documentMemberships.userId, userId)))
    .limit(1);
  return row?.role ?? null;
}

// Returns the document + the caller's role, or null if they aren't a member.
export async function getDocumentForUser(documentId: string, userId: string) {
  const [row] = await db
    .select({
      id: documents.id,
      title: documents.title,
      ownerId: documents.ownerId,
      role: documentMemberships.role,
      createdAt: documents.createdAt,
      updatedAt: documents.updatedAt,
    })
    .from(documents)
    .innerJoin(documentMemberships, eq(documentMemberships.documentId, documents.id))
    .where(and(eq(documents.id, documentId), eq(documentMemberships.userId, userId)))
    .limit(1);

  return row ?? null;
}

export async function renameDocument(documentId: string, title: string) {
  await db
    .update(documents)
    .set({ title: title.trim() || "Untitled", updatedAt: sql`now()` })
    .where(eq(documents.id, documentId));
}

// FK cascades remove memberships, updates, and snapshots with the document.
export async function deleteDocument(documentId: string) {
  await db.delete(documents).where(eq(documents.id, documentId));
}

// All members on a document, joined against users so the UI has emails/names
// to render without a second round-trip.
export async function listDocumentMembers(documentId: string) {
  return db
    .select({
      userId: users.id,
      email: users.email,
      name: users.name,
      role: documentMemberships.role,
      createdAt: documentMemberships.createdAt,
    })
    .from(documentMemberships)
    .innerJoin(users, eq(users.id, documentMemberships.userId))
    .where(eq(documentMemberships.documentId, documentId))
    .orderBy(asc(documentMemberships.createdAt));
}

// Insert a membership. Returns false if one already exists (unique index would
// otherwise throw). Kept idempotent so retries from a flaky client are safe.
export async function addDocumentMember(
  documentId: string,
  userId: string,
  role: DocRole,
): Promise<boolean> {
  const inserted = await db
    .insert(documentMemberships)
    .values({ documentId, userId, role })
    .onConflictDoNothing()
    .returning({ id: documentMemberships.id });
  return inserted.length > 0;
}

export async function updateMemberRole(documentId: string, userId: string, role: DocRole) {
  await db
    .update(documentMemberships)
    .set({ role })
    .where(
      and(
        eq(documentMemberships.documentId, documentId),
        eq(documentMemberships.userId, userId),
      ),
    );
}

export async function removeDocumentMember(documentId: string, userId: string) {
  await db
    .delete(documentMemberships)
    .where(
      and(
        eq(documentMemberships.documentId, documentId),
        eq(documentMemberships.userId, userId),
      ),
    );
}

// Create a document and its owner membership atomically. The id is generated by
// the client (so a doc created offline keeps a stable id), and the inserts are
// onConflictDoNothing so replaying the same create from the outbox is idempotent.
// One batch = one Neon transaction (the http driver has no interactive ones).
export async function createDocument(input: { id: string; ownerId: string; title?: string }) {
  await db.batch([
    db
      .insert(documents)
      .values({
        id: input.id,
        ownerId: input.ownerId,
        title: input.title?.trim() || "Untitled",
      })
      .onConflictDoNothing(),
    db
      .insert(documentMemberships)
      .values({
        documentId: input.id,
        userId: input.ownerId,
        role: "owner",
      })
      .onConflictDoNothing(),
  ]);

  return input.id;
}
